#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f lightgen.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace lightgen.sv --exe lightgen_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vlightgen.mk Vlightgen

# run executable simulation file
echo "\nRunning simulation"
obj_dir/Vlightgen
echo "\nSimulation completed"
